#!/bin/bash

while getopts hf:o:i:n:w opt; do
  case $opt in
    h)
      echo ""
      echo " ------------------------------------------------------------------------------ "
      echo " superdenss is a simple wrapper for denss that automates the process of "
      echo " generating multiple density reconstructions and averaging them with EMAN2. "
      echo ""
      echo " -f: filename of .dat solution scattering data"
      echo " -o: the output prefix to name the output directory and all the files."
      echo " -i: input options for denss exactly as they would be given to denss, including"
      echo "     dashed options. Enclose everything in quotes. Dont include --file or --output."
      echo " -n: the number of reconstructions to run (default 20)"
      echo " -w: overwrite the existing folder (appends/increments folder index if not given)"
      echo " ----------------------------------------------------------------------------- "
      echo ""
      exit 0
      ;;
    f)
      file=$OPTARG
      ;;
    o)
      output=$OPTARG
      ;;
    i)
      options=$OPTARG
      ;;
    n)
      n=$OPTARG
      ;;
    w)
      overwrite=True
      ;;
   \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." #>&2
      exit 1
      ;;
  esac
done

id=$output
if [ -z $n ]; then n=20 ; fi
range=`eval echo {0..$((n-1))}`
dir=${output}
newdir=$dir
dirn=0

if [ "$overwrite" != "True" ];
then
    until [ ! -d "${newdir}" ];
    do
        newdir=${dir}_${dirn}
        let dirn++
    done
fi

if [ ! -d "${newdir}" ];
then
    mkdir $newdir
fi

cd $newdir
cp ../${file} .
pwd

parallel denss.py -f \{1} -o \{2}_{3} ${options} ::: ${file} ::: ${id} ::: ${range}

for j in ${id}*[0-9].xplor; do map2map ${j} ${j%.*}.mrc <<< '2' ; done
ngrid=`awk 'NR==5 {print $1-1}' ${id[i]}_0.xplor`
e2buildstacks.py --stackname ${id}.hdf *.mrc
e2proc3d.py ${id}.hdf ${id}_resized.hdf --clip ${ngrid}
e2spt_classaverage.py --input ${id}_resized.hdf --parallel=thread:20 --saveali --savesteps --keep 3.0 --keepsig



























